trailingComma: "es5"
semi: true
singleQuote: false
plugins:
  - "./node_modules/@trivago/prettier-plugin-sort-imports/lib/src/index.js"
importOrder:
  - "^bun$"
  - "<THIRD_PARTY_MODULES>"
  - "^~"
  - "^[./]"
importOrderSeparation: true
importOrderSortSpecifiers: true
